### ISSUE TITLE
Somone please help I'm getting this issue but I have no idea what it means. thanks

### ISSUE THREAD

**Issue by hendrash** [FleekHQ/space-sdk#71] opened 2021-04-20 23:15 UTC
Deploy started at 7:09:11 PM 04/20/2021

7:09:12 PM 04/20/2021: Deploy started
7:09:15 PM 04/20/2021: Docker image: 'fleek/create-react-app'
7:09:15 PM 04/20/2021: Build command: 'yarn && yarn build'
7:09:15 PM 04/20/2021: Triggering build execution...
7:10:14 PM 04/20/2021: yarn install v1.22.5
7:10:14 PM 04/20/2021: [1/4] Resolving packages...
7:10:15 PM 04/20/2021: [2/4] Fetching packages...
7:10:25 PM 04/20/2021: error Command failed.
7:10:25 PM 04/20/2021: Exit code: 128
7:10:25 PM 04/20/2021: Command: git
7:10:25 PM 04/20/2021: Arguments: ls-remote --tags --heads ssh://git@github.com/ethereumjs/ethereumjs-abi.git
7:10:25 PM 04/20/2021: Directory: /workspace
7:10:25 PM 04/20/2021: Output:
7:10:25 PM 04/20/2021: Host key verification failed.
7:10:25 PM 04/20/2021: fatal: Could not read from remote repository.
7:10:25 PM 04/20/2021: Please make sure you have the correct access rights
7:10:25 PM 04/20/2021: and the repository exists.
7:10:25 PM 04/20/2021: info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
7:11:15 PM 04/20/2021: Error occured during the build.

**Comment by jsonsivar** [comment] 2021-04-30 03:54
Hi @hendrash - this seems to be an issue with using the `git` command with `ssh` in the build step. I don't think our containers support that by default so will look into this and get back to you.  Do you know which package is issuing that `git ls-remote` command?

On a side note - is this specifically related to the `space-sdk`? If not perhaps we can close the issue here and continue the discussion in our public Slack (https://slack.fleek.co).

**Comment by jsonsivar** [comment] 2021-04-30 14:33
Closing this as it seems to be a duplicate of https://github.com/FleekHQ/fleek-storage-js/issues/25. cc @hendrash @SamueleA

**Closed by jsonsivar** 2021-04-30 14:33 UTC
